"use client";
import { useState } from "react";

type Settings={high_threshold:number;medium_threshold:number;auto_approve_enabled:boolean;auto_approve_threshold:number;minimum_evaluated_samples:number;minimum_precision:number};
export function AiQualitySettings({initial}:{initial:Settings}) {
  const [settings,setSettings]=useState(initial),[message,setMessage]=useState("");
  const number=(key:keyof Settings,value:string)=>setSettings(current=>({...current,[key]:Number(value)}));
  async function save(){setMessage("保存中…");const response=await fetch("/api/admin/ai-quality",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(settings)});const data=await response.json();setMessage(response.ok?"保存しました":data.error);}
  async function evaluate(){setMessage("評価中…");const response=await fetch("/api/admin/ai-quality",{method:"POST"});const data=await response.json();setMessage(response.ok?"評価スナップショットを作成しました":data.error);if(response.ok)location.reload();}
  return <section className="rounded-2xl border border-slate-800 bg-slate-900/40 p-6"><h2 className="text-lg font-bold">品質ゲート設定</h2><p className="mt-2 text-sm text-slate-400">自動承認は評価ゲート通過後のみ有効になります。初期状態はOFFです。</p><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="高信頼閾値" value={settings.high_threshold} onChange={value=>number("high_threshold",value)}/><Field label="中信頼閾値" value={settings.medium_threshold} onChange={value=>number("medium_threshold",value)}/><Field label="自動承認閾値" value={settings.auto_approve_threshold} onChange={value=>number("auto_approve_threshold",value)}/><Field label="最低評価サンプル数" value={settings.minimum_evaluated_samples} step="1" onChange={value=>number("minimum_evaluated_samples",value)}/><Field label="必要精度" value={settings.minimum_precision} onChange={value=>number("minimum_precision",value)}/><label className="flex items-center gap-3 rounded-xl border border-slate-800 p-4 text-sm"><input type="checkbox" checked={settings.auto_approve_enabled} onChange={event=>setSettings(current=>({...current,auto_approve_enabled:event.target.checked}))}/>安全条件を満たした候補を自動承認</label></div><div className="mt-5 flex flex-wrap gap-3"><button onClick={save} className="rounded-lg bg-violet-600 px-4 py-2 text-sm">設定を保存</button><button onClick={evaluate} className="rounded-lg bg-slate-800 px-4 py-2 text-sm">現在の精度を評価</button>{message&&<span className="self-center text-sm text-slate-400">{message}</span>}</div></section>;
}
function Field({label,value,onChange,step="0.01"}:{label:string;value:number;onChange:(value:string)=>void;step?:string}){return <label className="text-sm text-slate-400">{label}<input type="number" min="0" max={step==="1"?"100000":"1"} step={step} value={value} onChange={event=>onChange(event.target.value)} className="mt-1 h-11 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 text-white"/></label>}
