"use client";
import { useState } from "react";

export function OperationsPanel({affiliate}:{affiliate:{enabled:boolean;affiliate_id?:string|null;url_template:string|null}}){
  const [message,setMessage]=useState(""),[template,setTemplate]=useState(affiliate.url_template??""),[affiliateId,setAffiliateId]=useState(affiliate.affiliate_id??""),[enabled,setEnabled]=useState(affiliate.enabled);
  async function run(body:Record<string,unknown>){setMessage("処理中…");const response=await fetch("/api/admin/operations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await response.json();setMessage(response.ok?`完了: ${JSON.stringify(data)}`:data.error??"失敗しました");}
  return <div className="space-y-6"><section className="rounded-2xl border border-slate-800 bg-slate-900/40 p-6"><h2 className="font-bold">自動化ジョブ</h2><div className="mt-4 flex flex-wrap gap-3"><Button onClick={()=>run({action:"collect"})}>X収集を実行</Button><Button onClick={()=>run({action:"enrich"})}>AI判定を実行</Button><Button onClick={()=>run({action:"metrics"})}>ランキング・分析更新</Button><Button onClick={()=>run({action:"affiliate"})}>未設定リンクを一括付与</Button></div></section><section className="rounded-2xl border border-slate-800 bg-slate-900/40 p-6"><h2 className="font-bold">アフィリエイト自動付与</h2><p className="mt-2 text-sm text-slate-400">テンプレートを一度設定すれば、以後はアフィリエイトIDを1つ登録するだけで全作品へ反映できます。</p><label className="mt-4 block text-sm text-slate-400">アフィリエイトID<input value={affiliateId} onChange={event=>setAffiliateId(event.target.value)} placeholder="example-001" className="mt-1 h-11 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 text-white"/></label><details className="mt-4"><summary className="cursor-pointer text-sm text-slate-400">URLテンプレート（初回のみ）</summary><input value={template} onChange={event=>setTemplate(event.target.value)} placeholder="https://example.com/{product_code}?affiliate={affiliate_id}" className="mt-3 h-11 w-full rounded-lg border border-slate-700 bg-slate-950 px-3"/></details><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={enabled} onChange={event=>setEnabled(event.target.checked)}/>新規・更新作品へ自動付与</label><button onClick={()=>run({action:"affiliate-settings",enabled,affiliate_id:affiliateId||null,url_template:template||null})} className="mt-4 rounded-lg bg-violet-600 px-4 py-2 text-sm">設定を保存</button></section>{message&&<pre className="overflow-auto rounded-xl bg-slate-950 p-4 text-xs text-slate-300">{message}</pre>}</div>;
}
function Button({children,onClick}:{children:React.ReactNode;onClick:()=>void}){return <button onClick={onClick} className="rounded-lg bg-slate-800 px-4 py-2 text-sm hover:bg-slate-700">{children}</button>}
