"use client";
import { useCallback, useEffect, useState } from "react";
import { ImageIcon, Pencil, Plus, Search, Trash2, X } from "lucide-react";
import Image from "next/image";

type Work = {
  id:string;product_code:string;title:string;actress_name:string|null;maker_name:string|null;series_name:string|null;
  label_name:string|null;genre:string|null;duration:number|null;release_date:string|null;sample_images:string[];card_thumbnail_url:string|null;thumbnail_url:string|null;
  video_url:string|null;official_url:string|null;affiliate_url:string|null;source_name:string|null;external_product_id:string|null;description:string|null;
  is_published:boolean;content_category:"commercial_av"|"creator"|"doujin";
};
type Form = Omit<Work,"id">;
const empty:Form={product_code:"",title:"",actress_name:null,maker_name:null,series_name:null,label_name:null,genre:null,duration:null,release_date:null,sample_images:[],card_thumbnail_url:null,thumbnail_url:null,video_url:null,official_url:null,affiliate_url:null,source_name:null,external_product_id:null,description:null,is_published:false,content_category:"commercial_av"};
const textFields:[keyof Form,string][]=[["product_code","品番 *"],["title","タイトル *"],["actress_name","女優名"],["maker_name","メーカー名"],["series_name","シリーズ名"],["label_name","レーベル"],["genre","ジャンル"],["release_date","発売日"],["source_name","出典名（例：FANZA公式商品ページ）"],["external_product_id","公式の外部商品ID"],["card_thumbnail_url","カード専用画像URL"],["thumbnail_url","作品詳細メイン画像URL"],["video_url","公式提供の動画URL"],["official_url","通常の公式商品URL"],["affiliate_url","承認済みサイト専用のアフィリエイトURL"]];

export function WorksManager(){
  const [items,setItems]=useState<Work[]>([]),[count,setCount]=useState(0),[page,setPage]=useState(1),[query,setQuery]=useState("");
  const [editing,setEditing]=useState<Work|null>(null),[form,setForm]=useState<Form>(empty),[open,setOpen]=useState(false);
  const [cardEditing,setCardEditing]=useState<Work|null>(null),[cardUrl,setCardUrl]=useState("");
  const [busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const load=useCallback(async()=>{setBusy(true);const response=await fetch(`/api/admin/works?q=${encodeURIComponent(query)}&page=${page}`,{cache:"no-store"});const body=await response.json();if(response.ok){setItems(body.items);setCount(body.count)}else setMessage(body.error??"取得に失敗しました");setBusy(false)},[page,query]);
  useEffect(()=>{void load()},[load]);
  function start(work?:Work){setEditing(work??null);setForm(work?Object.fromEntries(Object.entries(work).filter(([key])=>key!=="id")) as Form:empty);setMessage("");setOpen(true)}
  function startCardEdit(work:Work){setCardEditing(work);setCardUrl(work.card_thumbnail_url??"");setMessage("")}
  function imageCandidates(work:Work){const generated=`/card-thumbnails/${work.product_code}.jpg`;const candidates:[string,string|null][]=[["現在の代表画像",work.card_thumbnail_url],["パッケージ / DVD全面",work.thumbnail_url],["DVD右側表紙（生成済みの場合）",generated],...(work.sample_images??[]).slice(0,12).map((url,index)=>[`サンプル${index+1}`,url] as [string,string|null])];const seen=new Set<string>();return candidates.filter(([,url])=>{if(!url||seen.has(url))return false;seen.add(url);return true})}
  function set<K extends keyof Form>(key:K,value:Form[K]){setForm(current=>({...current,[key]:value}))}
  async function save(){setBusy(true);setMessage("");const payload={...form,duration:form.duration===null?null:Number(form.duration),...editing?{id:editing.id}:{}};const response=await fetch("/api/admin/works",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const body=await response.json();if(response.ok){setOpen(false);setMessage(editing?"更新しました":"追加しました");await load()}else setMessage(body.error??"保存に失敗しました");setBusy(false)}
  async function saveCardOnly(){if(!cardEditing)return;setBusy(true);setMessage("");const {id,...base}=cardEditing;const payload={...base,id,card_thumbnail_url:cardUrl.trim()||null,duration:base.duration===null?null:Number(base.duration)};const response=await fetch("/api/admin/works",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const body=await response.json();if(response.ok){setCardEditing(null);setMessage("カード画像URLを更新しました");await load()}else setMessage(body.error??"カード画像URLの保存に失敗しました");setBusy(false)}
  async function remove(work:Work){if(!confirm(`${work.product_code} を削除しますか？この操作は取り消せません。`))return;setBusy(true);const response=await fetch(`/api/admin/works?id=${work.id}`,{method:"DELETE"});const body=await response.json();setMessage(response.ok?"削除しました":body.error??"削除に失敗しました");if(response.ok)await load();setBusy(false)}
  return <div className="space-y-5">
    <div className="flex flex-col gap-3 sm:flex-row"><form className="flex flex-1 gap-2" onSubmit={event=>{event.preventDefault();setPage(1);void load()}}><div className="relative flex-1"><Search className="absolute left-3 top-3 size-4 text-slate-500"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="品番・タイトル・女優・メーカー" className="h-10 w-full rounded-lg border border-slate-700 bg-slate-950 pl-9 pr-3 text-sm"/></div><button className="rounded-lg border border-slate-700 px-4 text-sm">検索</button></form><button onClick={()=>start()} className="flex h-10 items-center justify-center gap-2 rounded-lg bg-violet-600 px-4 text-sm font-bold"><Plus className="size-4"/>作品を追加</button></div>
    <div className="rounded-xl border border-violet-900/50 bg-violet-950/20 p-4 text-xs leading-6 text-violet-100">カード画像は「代表画像」です。自動95%・手動5%で運用し、普通のプレイシーンではなく、縦長パッケージ・文字入り/ポスター風サンプル・DVD右側表紙だけを採用します。</div>
    {message&&<p className="rounded-lg border border-slate-700 bg-slate-900 px-4 py-3 text-sm">{message}</p>}
    <div className="overflow-x-auto rounded-xl border border-slate-800"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-900 text-slate-400"><tr><th className="p-3">現在の代表画像</th><th className="p-3">品番・タイトル</th><th className="p-3">公開</th><th className="p-3">女優</th><th className="p-3">メーカー</th><th className="p-3">シリーズ</th><th className="p-3 text-right">操作</th></tr></thead><tbody>{items.map(work=><tr key={work.id} className="border-t border-slate-800"><td className="p-3">{work.card_thumbnail_url?<Image src={work.card_thumbnail_url} alt="" width={64} height={84} unoptimized className="h-20 w-14 rounded bg-slate-950 object-contain"/>:<span className="grid h-20 w-14 place-items-center rounded bg-slate-900 text-center font-mono text-[9px] leading-3 tracking-widest text-slate-600">NOW<br/>PRINTING</span>}</td><td className="p-3"><b>{work.product_code}</b><p className="mt-1 max-w-md truncate text-slate-400">{work.title}</p>{!work.card_thumbnail_url&&<p className="mt-1 text-xs text-amber-300">代表画像なし</p>}</td><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs ${work.is_published?"bg-emerald-950 text-emerald-300":"bg-slate-800 text-slate-400"}`}>{work.is_published?"公開":"非公開"}</span></td><td className="p-3">{work.actress_name??"—"}</td><td className="p-3">{work.maker_name??"—"}</td><td className="p-3">{work.series_name??"—"}</td><td className="p-3"><div className="flex justify-end gap-2"><button aria-label="代表画像を選ぶ" onClick={()=>startCardEdit(work)} className="rounded-lg border border-violet-800 p-2 text-violet-300"><ImageIcon className="size-4"/></button><button aria-label="編集" onClick={()=>start(work)} className="rounded-lg border border-slate-700 p-2"><Pencil className="size-4"/></button><button aria-label="削除" onClick={()=>void remove(work)} className="rounded-lg border border-red-900 p-2 text-red-400"><Trash2 className="size-4"/></button></div></td></tr>)}</tbody></table>{!busy&&!items.length&&<p className="p-8 text-center text-sm text-slate-500">作品がありません。</p>}</div>
    <div className="flex items-center justify-between text-sm text-slate-400"><span>{count.toLocaleString()}件</span><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(value=>value-1)} className="rounded border border-slate-700 px-3 py-1 disabled:opacity-40">前へ</button><span>{page} / {Math.max(1,Math.ceil(count/30))}</span><button disabled={page*30>=count} onClick={()=>setPage(value=>value+1)} className="rounded border border-slate-700 px-3 py-1 disabled:opacity-40">次へ</button></div></div>
    {open&&<div className="fixed inset-0 z-50 overflow-y-auto bg-black/75 p-4"><div className="mx-auto my-6 max-w-3xl rounded-2xl border border-slate-700 bg-slate-950 p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">{editing?"作品を編集":"作品を追加"}</h2><button onClick={()=>setOpen(false)}><X/></button></div><div className="mt-4 rounded-lg border border-amber-800/70 bg-amber-950/30 p-3 text-xs leading-5 text-amber-200">審査前は通常の公式商品URLだけを入力し、アフィリエイトURLは空欄にしてください。画像は公式に利用を許可されたURLだけを使用し、説明文は転載せず独自に記述してください。</div><div className="mt-5 grid gap-4 sm:grid-cols-2">{textFields.map(([key,label])=><label key={key} className={key==="title"||key.toString().includes("url")?"sm:col-span-2":""}><span className="text-xs text-slate-400">{label}</span><input type={key==="release_date"?"date":"text"} value={String(form[key]??"")} onChange={event=>set(key,event.target.value.trim()===""?null:event.target.value as never)} className="mt-1 h-10 w-full rounded-lg border border-slate-700 bg-slate-900 px-3 text-sm"/></label>)}<label><span className="text-xs text-slate-400">再生時間（分）</span><input type="number" min="0" value={form.duration??""} onChange={event=>set("duration",event.target.value===""?null:Number(event.target.value))} className="mt-1 h-10 w-full rounded-lg border border-slate-700 bg-slate-900 px-3 text-sm"/></label><label><span className="text-xs text-slate-400">カテゴリ</span><select value={form.content_category} onChange={event=>set("content_category",event.target.value as Form["content_category"])} className="mt-1 h-10 w-full rounded-lg border border-slate-700 bg-slate-900 px-3 text-sm"><option value="commercial_av">商業AV作品</option><option value="creator">個人クリエイター（将来用）</option><option value="doujin">同人作品（将来用）</option></select></label><label className="flex items-center gap-3 rounded-lg border border-slate-700 p-3"><input type="checkbox" checked={form.is_published} onChange={event=>set("is_published",event.target.checked)}/><span className="text-sm">公開する（出典・販売先確認後のみ）</span></label><label className="sm:col-span-2"><span className="text-xs text-slate-400">独自紹介文（公式説明文の転載禁止）</span><textarea value={form.description??""} onChange={event=>set("description",event.target.value||null)} rows={4} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-900 p-3 text-sm"/></label></div><div className="mt-6 flex justify-end gap-3"><button onClick={()=>setOpen(false)} className="rounded-lg border border-slate-700 px-4 py-2 text-sm">キャンセル</button><button disabled={busy||!form.product_code||!form.title} onClick={()=>void save()} className="rounded-lg bg-violet-600 px-5 py-2 text-sm font-bold disabled:opacity-40">保存</button></div></div></div>}
    {cardEditing&&<div className="fixed inset-0 z-50 overflow-y-auto bg-black/75 p-4"><div className="mx-auto my-6 w-full max-w-4xl rounded-2xl border border-slate-700 bg-slate-950 p-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">代表画像を選ぶ</h2><p className="mt-1 text-sm text-slate-400">{cardEditing.product_code} / {cardEditing.title}</p></div><button onClick={()=>setCardEditing(null)}><X/></button></div><p className="mt-4 rounded-lg border border-violet-900/60 bg-violet-950/25 p-3 text-xs leading-5 text-violet-100">採用するのは「一覧で魅力的に見える代表画像」だけです。普通のプレイシーン・ただの静止画は選ばず、縦長パッケージ、文字入り/ポスター風サンプル、DVD右側表紙を選んでください。</p><div className="mt-5 grid gap-4 md:grid-cols-[180px_1fr]"><div>{cardUrl?<Image src={cardUrl} alt="" width={180} height={240} unoptimized className="h-60 w-full rounded-xl bg-slate-900 object-contain"/>:<span className="grid h-60 w-full place-items-center rounded-xl bg-slate-900 text-center font-mono text-sm font-semibold tracking-[0.24em] text-slate-600">NOW<br/>PRINTING</span>}<p className="mt-2 text-center text-xs text-slate-500">現在の代表画像</p><button type="button" onClick={()=>setCardUrl("")} className="mt-3 w-full rounded-lg border border-slate-700 px-3 py-2 text-xs text-slate-300 hover:bg-slate-900">NOW PRINTINGにする</button></div><div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{imageCandidates(cardEditing).map(([label,url])=><button key={`${label}:${url}`} type="button" onClick={()=>setCardUrl(url??"")} className={`rounded-xl border p-2 text-left transition active:scale-[0.98] ${cardUrl===url?"border-violet-400 bg-violet-950/40":"border-slate-800 bg-slate-900/50 hover:border-slate-600"}`}><Image src={url??""} alt="" width={140} height={180} unoptimized className="h-36 w-full rounded-lg bg-slate-950 object-contain"/><span className="mt-2 block truncate text-xs text-slate-300">{label}</span></button>)}</div><label className="mt-4 block"><span className="text-xs text-slate-400">card_thumbnail_url</span><input value={cardUrl} onChange={event=>setCardUrl(event.target.value)} placeholder="https://... または /card-thumbnails/..." className="mt-1 h-10 w-full rounded-lg border border-slate-700 bg-slate-900 px-3 text-sm"/><p className="mt-2 text-xs leading-5 text-slate-500">1クリック候補で足りない場合だけURLを手入力します。他の作品情報は変更しません。</p></label></div></div><div className="mt-6 flex justify-end gap-3"><button onClick={()=>setCardEditing(null)} className="rounded-lg border border-slate-700 px-4 py-2 text-sm">キャンセル</button><button disabled={busy} onClick={()=>void saveCardOnly()} className="rounded-lg bg-violet-600 px-5 py-2 text-sm font-bold disabled:opacity-40">代表画像だけ保存</button></div></div></div>}
  </div>
}
