/* This file is generated by scripts/generate-thumbnail-phase4e-reviewed-decisions.mjs. */
/* Do not edit it by hand. It is static and safe for client bundles. */

import type { CanonicalDecisionRecord } from "./adapters.ts";

export const GENERATED_PHASE4E_REVIEWED_DECISION_RECORDS = Object.freeze(
  [
  {
    "code": "KIWVR00907",
    "mode": "SAMPLE",
    "state": "RESOLVED",
    "source_id": "sample:1",
    "source_path_or_url": "https://pics.dmm.co.jp/digital/video/kiwvr00907/kiwvr00907jp-1.jpg",
    "source_hash": "6617d270aaca3b1072f2537894ef854d972dde127094c7d717ddff6981cdacf8",
    "output_path_or_url": "https://pics.dmm.co.jp/digital/video/kiwvr00907/kiwvr00907jp-1.jpg",
    "output_hash": "6617d270aaca3b1072f2537894ef854d972dde127094c7d717ddff6981cdacf8",
    "crop_spec": null,
    "approved_by": "USER_HANDOFF",
    "approved_at": "2026-08-03",
    "approval_batch": "PHASE_4E_USER_REVIEW",
    "reason": "Phase 4E全候補の7:10カード表示をユーザーが比較し sample:1を作品の正解として承認; Phase 4C/4Dの旧decisionを置換"
  },
  {
    "code": "KSBJ00438",
    "mode": "SAMPLE",
    "state": "RESOLVED",
    "source_id": "sample:1",
    "source_path_or_url": "https://pics.dmm.co.jp/digital/video/ksbj00438/ksbj00438jp-1.jpg",
    "source_hash": "e2bf85d60b077c2b269d3a7a40f7c9082ba299e712f783ff9948d21c4f890ec6",
    "output_path_or_url": "https://pics.dmm.co.jp/digital/video/ksbj00438/ksbj00438jp-1.jpg",
    "output_hash": "e2bf85d60b077c2b269d3a7a40f7c9082ba299e712f783ff9948d21c4f890ec6",
    "crop_spec": null,
    "approved_by": "USER_HANDOFF",
    "approved_at": "2026-08-03",
    "approval_batch": "PHASE_4E_USER_REVIEW",
    "reason": "Phase 4E全候補の7:10カード表示をユーザーが比較し sample:1を作品の正解として承認; Phase 4C/4Dの旧decisionを置換"
  },
  {
    "code": "LUCY00029",
    "mode": "SAMPLE",
    "state": "RESOLVED",
    "source_id": "sample:1",
    "source_path_or_url": "https://pics.dmm.co.jp/digital/video/lucy00029/lucy00029jp-1.jpg",
    "source_hash": "428ed0e1dc8c0714c371672f5287b4c1cfcc67561d52740f9ec10e5b6867c203",
    "output_path_or_url": "https://pics.dmm.co.jp/digital/video/lucy00029/lucy00029jp-1.jpg",
    "output_hash": "428ed0e1dc8c0714c371672f5287b4c1cfcc67561d52740f9ec10e5b6867c203",
    "crop_spec": null,
    "approved_by": "USER_HANDOFF",
    "approved_at": "2026-08-03",
    "approval_batch": "PHASE_4E_USER_REVIEW",
    "reason": "Phase 4E全候補の7:10カード表示をユーザーが比較し sample:1を作品の正解として承認; Phase 4C/4Dの旧decisionを置換"
  },
  {
    "code": "UMSO00650",
    "mode": "SAMPLE",
    "state": "RESOLVED",
    "source_id": "sample:1",
    "source_path_or_url": "https://pics.dmm.co.jp/digital/video/umso00650/umso00650jp-1.jpg",
    "source_hash": "03bf532f7aae96fc466c825558af559ff6ac30aa61c0ce285b77bda84ad4fb21",
    "output_path_or_url": "https://pics.dmm.co.jp/digital/video/umso00650/umso00650jp-1.jpg",
    "output_hash": "03bf532f7aae96fc466c825558af559ff6ac30aa61c0ce285b77bda84ad4fb21",
    "crop_spec": null,
    "approved_by": "USER_HANDOFF",
    "approved_at": "2026-08-03",
    "approval_batch": "PHASE_4E_USER_REVIEW",
    "reason": "Phase 4E全候補の7:10カード表示をユーザーが比較し sample:1を作品の正解として承認; Phase 4C/4Dの旧decisionを置換"
  }
] as const satisfies readonly CanonicalDecisionRecord[],
);

export const GENERATED_PHASE4E_REVIEWED_STATS = Object.freeze(
  {
  "total": 4,
  "SAMPLE": 4,
  "auto_applied": 0
} as const,
);

export const GENERATED_PHASE4E_REVIEWED_INPUT_SHA256 = "538c159793d279ab3d9bb026e7e1ca1e4dc6b47202d413c4bc71fa046b9abcb9";
