/* This file is generated by scripts/generate-thumbnail-phase4c-reviewed-decisions.mjs. */
/* Do not edit it by hand. It is static and safe for client bundles. */

import type { CanonicalDecisionRecord } from "./adapters.ts";

export const GENERATED_PHASE4C_REVIEWED_DECISION_RECORDS = Object.freeze(
  [
  {
    "code": "DSOD00029",
    "mode": "PACKAGE_RIGHT",
    "state": "RESOLVED",
    "source_id": "dvd:right",
    "source_path_or_url": "public/card-thumbnails/DSOD00029-auto-right.jpg",
    "source_hash": "861698722fe5183bbfe1f0e58b4e6eb22d3366df056dff0cdd1e798ec471dc64",
    "output_path_or_url": "/card-thumbnails/DSOD00029-auto-right.jpg",
    "output_hash": "861698722fe5183bbfe1f0e58b4e6eb22d3366df056dff0cdd1e798ec471dc64",
    "crop_spec": null,
    "approved_by": "USER_HANDOFF",
    "approved_at": "2026-08-02",
    "reason": "User approved the Phase 4C PACKAGE_RIGHT recommendation; title person and work information remain representative without image transformation"
  },
  {
    "code": "DVMM00422",
    "mode": "PACKAGE_RIGHT",
    "state": "RESOLVED",
    "source_id": "dvd:right",
    "source_path_or_url": "public/card-thumbnails/DVMM00422-auto-right.jpg",
    "source_hash": "9d9184f7b948ba567898cbf6fb8448bfcf2e106880c2b0a063b4a9d296ce2030",
    "output_path_or_url": "/card-thumbnails/DVMM00422-auto-right.jpg",
    "output_hash": "9d9184f7b948ba567898cbf6fb8448bfcf2e106880c2b0a063b4a9d296ce2030",
    "crop_spec": null,
    "approved_by": "USER_HANDOFF",
    "approved_at": "2026-08-02",
    "reason": "User approved the Phase 4C PACKAGE_RIGHT recommendation; title and subject remain clear without image transformation"
  },
  {
    "code": "DVMM00423",
    "mode": "PACKAGE_RIGHT",
    "state": "RESOLVED",
    "source_id": "dvd:right",
    "source_path_or_url": "public/card-thumbnails/DVMM00423-auto-right.jpg",
    "source_hash": "4bf0d609d3f2a3bf67539e176bae33bea1a3d46e95893c0d4c8ae2193279f3d4",
    "output_path_or_url": "/card-thumbnails/DVMM00423-auto-right.jpg",
    "output_hash": "4bf0d609d3f2a3bf67539e176bae33bea1a3d46e95893c0d4c8ae2193279f3d4",
    "crop_spec": null,
    "approved_by": "USER_HANDOFF",
    "approved_at": "2026-08-02",
    "reason": "User approved the Phase 4C PACKAGE_RIGHT recommendation; title subject and composition remain representative without image transformation"
  },
  {
    "code": "H_237NACT00155",
    "mode": "PACKAGE_RIGHT",
    "state": "RESOLVED",
    "source_id": "dvd:right",
    "source_path_or_url": "public/card-thumbnails/H_237NACT00155-auto-right.jpg",
    "source_hash": "5697e97a64e7059f5cc2f2e0d7ba2383c26f247f8fe9b0eb112bc26ebaebba70",
    "output_path_or_url": "/card-thumbnails/H_237NACT00155-auto-right.jpg",
    "output_hash": "5697e97a64e7059f5cc2f2e0d7ba2383c26f247f8fe9b0eb112bc26ebaebba70",
    "crop_spec": null,
    "approved_by": "USER_HANDOFF",
    "approved_at": "2026-08-02",
    "reason": "User approved the Phase 4C PACKAGE_RIGHT recommendation; title and subject best represent the work without image transformation"
  },
  {
    "code": "H_237NACT00158",
    "mode": "PACKAGE_RIGHT",
    "state": "RESOLVED",
    "source_id": "dvd:right",
    "source_path_or_url": "public/card-thumbnails/H_237NACT00158-auto-right.jpg",
    "source_hash": "33b4c8fcafeaeeadaae472738312e64a8a7b16c8594ca9bd88db211f2d02cb0f",
    "output_path_or_url": "/card-thumbnails/H_237NACT00158-auto-right.jpg",
    "output_hash": "33b4c8fcafeaeeadaae472738312e64a8a7b16c8594ca9bd88db211f2d02cb0f",
    "crop_spec": null,
    "approved_by": "USER_HANDOFF",
    "approved_at": "2026-08-02",
    "reason": "User approved the Phase 4C PACKAGE_RIGHT recommendation; title and subject remain representative without image transformation"
  },
  {
    "code": "H_237NACT00159",
    "mode": "PACKAGE_RIGHT",
    "state": "RESOLVED",
    "source_id": "dvd:right",
    "source_path_or_url": "public/card-thumbnails/H_237NACT00159-auto-right.jpg",
    "source_hash": "1981efdc5f894a5bef31fdb61348bfd1bb8abe672215afcdc8b845798341899e",
    "output_path_or_url": "/card-thumbnails/H_237NACT00159-auto-right.jpg",
    "output_hash": "1981efdc5f894a5bef31fdb61348bfd1bb8abe672215afcdc8b845798341899e",
    "crop_spec": null,
    "approved_by": "USER_HANDOFF",
    "approved_at": "2026-08-02",
    "reason": "User approved the Phase 4C PACKAGE_RIGHT recommendation; title subject and setting remain representative without image transformation"
  },
  {
    "code": "KIWVR00907",
    "mode": "SAMPLE",
    "state": "RESOLVED",
    "source_id": "sample:2",
    "source_path_or_url": "https://pics.dmm.co.jp/digital/video/kiwvr00907/kiwvr00907jp-2.jpg",
    "source_hash": "2d0eace3387a6de20d2654683590e1be959496d6fb28c463084d4b6ed6813869",
    "output_path_or_url": "https://pics.dmm.co.jp/digital/video/kiwvr00907/kiwvr00907jp-2.jpg",
    "output_hash": "2d0eace3387a6de20d2654683590e1be959496d6fb28c463084d4b6ed6813869",
    "crop_spec": null,
    "approved_by": "USER_HANDOFF",
    "approved_at": "2026-08-02",
    "reason": "User approved Phase 4C sample 2 because face upper body costume and scene are clear"
  },
  {
    "code": "KSBJ00438",
    "mode": "SAMPLE",
    "state": "RESOLVED",
    "source_id": "sample:5",
    "source_path_or_url": "https://pics.dmm.co.jp/digital/video/ksbj00438/ksbj00438jp-5.jpg",
    "source_hash": "58fce856873d542811ead2c4c9c95c4cf214da02625473c9481e84c64d2e72f2",
    "output_path_or_url": "https://pics.dmm.co.jp/digital/video/ksbj00438/ksbj00438jp-5.jpg",
    "output_hash": "58fce856873d542811ead2c4c9c95c4cf214da02625473c9481e84c64d2e72f2",
    "crop_spec": null,
    "approved_by": "USER_HANDOFF",
    "approved_at": "2026-08-02",
    "reason": "User approved Phase 4C sample 5 because faces relationship and scene remain representative"
  },
  {
    "code": "LUCY00029",
    "mode": "SAMPLE",
    "state": "RESOLVED",
    "source_id": "sample:3",
    "source_path_or_url": "https://pics.dmm.co.jp/digital/video/lucy00029/lucy00029jp-3.jpg",
    "source_hash": "d19655be001fc5d0d2ff9ab88f8b198f6feb4c46c19059f6361382f353fc08a5",
    "output_path_or_url": "https://pics.dmm.co.jp/digital/video/lucy00029/lucy00029jp-3.jpg",
    "output_hash": "d19655be001fc5d0d2ff9ab88f8b198f6feb4c46c19059f6361382f353fc08a5",
    "crop_spec": null,
    "approved_by": "USER_HANDOFF",
    "approved_at": "2026-08-02",
    "reason": "User approved Phase 4C sample 3 because both people and the scene are clear"
  },
  {
    "code": "MUDR00386",
    "mode": "SAMPLE",
    "state": "RESOLVED",
    "source_id": "sample:5",
    "source_path_or_url": "https://pics.dmm.co.jp/digital/video/mudr00386/mudr00386jp-5.jpg",
    "source_hash": "a44aee4739a8dfd89a0516d609676be748fed1a7a73c81e661aeaba5f5ef2362",
    "output_path_or_url": "https://pics.dmm.co.jp/digital/video/mudr00386/mudr00386jp-5.jpg",
    "output_hash": "a44aee4739a8dfd89a0516d609676be748fed1a7a73c81e661aeaba5f5ef2362",
    "crop_spec": null,
    "approved_by": "USER_HANDOFF",
    "approved_at": "2026-08-02",
    "reason": "User approved Phase 4C sample 5 because people props and story context are visible"
  },
  {
    "code": "NATR00771",
    "mode": "SAMPLE",
    "state": "RESOLVED",
    "source_id": "sample:1",
    "source_path_or_url": "https://pics.dmm.co.jp/digital/video/natr00771/natr00771jp-1.jpg",
    "source_hash": "8b563cc4e95a02888d997336810d9d5f1d9fc2f0172b30e2a51f141fce1a5294",
    "output_path_or_url": "https://pics.dmm.co.jp/digital/video/natr00771/natr00771jp-1.jpg",
    "output_hash": "8b563cc4e95a02888d997336810d9d5f1d9fc2f0172b30e2a51f141fce1a5294",
    "crop_spec": null,
    "approved_by": "USER_HANDOFF",
    "approved_at": "2026-08-02",
    "reason": "User approved Phase 4C sample 1 as the representative multi-work cover image"
  },
  {
    "code": "NIMA00081",
    "mode": "SAMPLE",
    "state": "RESOLVED",
    "source_id": "sample:18",
    "source_path_or_url": "https://pics.dmm.co.jp/digital/video/nima00081/nima00081jp-18.jpg",
    "source_hash": "6f3e6388b044cd18be67a6297ad649fa3c314a358f671511d045dcccccb01e4b",
    "output_path_or_url": "https://pics.dmm.co.jp/digital/video/nima00081/nima00081jp-18.jpg",
    "output_hash": "6f3e6388b044cd18be67a6297ad649fa3c314a358f671511d045dcccccb01e4b",
    "crop_spec": null,
    "approved_by": "USER_HANDOFF",
    "approved_at": "2026-08-02",
    "reason": "User approved Phase 4C sample 18 because both principal people and setting are clear"
  },
  {
    "code": "UMSO00649",
    "mode": "SAMPLE",
    "state": "RESOLVED",
    "source_id": "sample:1",
    "source_path_or_url": "https://pics.dmm.co.jp/digital/video/umso00649/umso00649jp-1.jpg",
    "source_hash": "331260ba0ed310433918069cd31ba17623950b416923453d22f22f8ea9bfc4a1",
    "output_path_or_url": "https://pics.dmm.co.jp/digital/video/umso00649/umso00649jp-1.jpg",
    "output_hash": "331260ba0ed310433918069cd31ba17623950b416923453d22f22f8ea9bfc4a1",
    "crop_spec": null,
    "approved_by": "USER_HANDOFF",
    "approved_at": "2026-08-02",
    "reason": "User approved Phase 4C sample 1 as the representative multi-person BEST cover image"
  },
  {
    "code": "UMSO00650",
    "mode": "SAMPLE",
    "state": "RESOLVED",
    "source_id": "sample:9",
    "source_path_or_url": "https://pics.dmm.co.jp/digital/video/umso00650/umso00650jp-9.jpg",
    "source_hash": "19c75d65de6ce4bf05e0fc5d8f90530cfa3dace934184ca6ed155dd252c08afc",
    "output_path_or_url": "https://pics.dmm.co.jp/digital/video/umso00650/umso00650jp-9.jpg",
    "output_hash": "19c75d65de6ce4bf05e0fc5d8f90530cfa3dace934184ca6ed155dd252c08afc",
    "crop_spec": null,
    "approved_by": "USER_HANDOFF",
    "approved_at": "2026-08-02",
    "reason": "User approved Phase 4C sample 9 because costume subject and recording context are clear"
  },
  {
    "code": "VRKM01857",
    "mode": "SAMPLE",
    "state": "RESOLVED",
    "source_id": "sample:1",
    "source_path_or_url": "https://pics.dmm.co.jp/digital/video/vrkm01857/vrkm01857jp-1.jpg",
    "source_hash": "9d5030d1d5d1b493018af60e42b670fda792b8d682682419b150d8c015bbbb8a",
    "output_path_or_url": "https://pics.dmm.co.jp/digital/video/vrkm01857/vrkm01857jp-1.jpg",
    "output_hash": "9d5030d1d5d1b493018af60e42b670fda792b8d682682419b150d8c015bbbb8a",
    "crop_spec": null,
    "approved_by": "USER_HANDOFF",
    "approved_at": "2026-08-02",
    "reason": "User approved Phase 4C sample 1 as the representative BEST cover image"
  }
] as const satisfies readonly CanonicalDecisionRecord[],
);

export const GENERATED_PHASE4C_REVIEWED_STATS = Object.freeze(
  {
  "total": 15,
  "SAMPLE": 9,
  "PACKAGE_RIGHT": 6
} as const,
);

export const GENERATED_PHASE4C_REVIEWED_INPUT_SHA256 = "b135eb40612be1febf9f045317072db59db4fd30cd543bdadb5f1c062afa386b";
